import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Menubar/header";
import MenuBar from "@/components/Menubar/menuBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta name="apple-mobile-web-app-capable" content="yes" />
      <meta
        name="apple-mobile-web-app-status-bar-style"
        content="black-translucent"
      ></meta>
      <body className={inter.className}>
        <div className="">
          <Header />
          <div className="relative h-full pt-36 overflow-y-scroll">
            {children}
          </div>
          <MenuBar />
        </div>
      </body>
    </html>
  );
}
